# -*- coding: utf-8 -*-
"""Numpy_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1slDOMtbyI_DYg2Q-OFqYlgOGRQIR37zL

NumPy運算速度:
"""

import time
import numpy as np 

def calculate():
  a = np. random.randn(100000)
  b = list(a)

  start = time.time()

  for i in range(1000):
    sum1 = np.sum(a)
  print('Using NumPy\t %f sec'%(time.time()-start))

  start_2= time.time()

  for j in range(1000):
    sum2 = sum(b)
  print("No Using NumPy\t %f sec"%(time.time()-start_2))

calculate()